version: '3.9'
services:
  generic:
    hostname: ${DC_HOSTNAME_GENERIC}
    image: magento/magento-cloud-docker-php:${DC_IMAGE_PHP_CLI_VERSION}
    env_file: ${DC_ENV_FILE_PATH}
    environment:
      - 'MAGENTO_ROOT=${MAGENTO_ROOT}'
      - 'MAGENTO_RUN_MODE=${MAGENTO_RUN_MODE}'
      - 'PHP_EXTENSIONS=${PHP_EXTENSIONS}'
      - 'SENDMAIL_PATH=/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025'
  deploy:
    hostname: ${DC_HOSTNAME_DEPLOY}
    image: magento/magento-cloud-docker-php:${DC_IMAGE_PHP_CLI_VERSION}
    extends: generic
    volumes:
      - './${MAGENTO_DIR}:${MAGENTO_ROOT}:delegated'
      - './${EXTENSIONS_DIR}:/extensions:delegated'
      - './${SHARED_DIR}:/mnt:rw,delegated'
      - '~/.composer/cache:/composer/cache'
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_DEPLOY}
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_healthy
  fpm:
    hostname: ${DC_HOSTNAME_FPM}
    image: magento/magento-cloud-docker-php:${DC_IMAGE_PHP_FPM_VERSION}
    extends: generic
    volumes:
      - './${MAGENTO_DIR}:${MAGENTO_ROOT}:delegated'
      - './${EXTENSIONS_DIR}:/extensions:delegated'
      - './${SHARED_DIR}:/mnt:rw,delegated'
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_FPM}
    depends_on:
      db:
        condition: service_healthy
  fpm_xdebug:
    hostname: ${DC_HOSTNAME_FPM_XDEBUG}
    image: magento/magento-cloud-docker-php:${DC_IMAGE_PHP_FPM_VERSION}
    extends: generic
    volumes:
      - './${MAGENTO_DIR}:${MAGENTO_ROOT}:delegated'
      - './${EXTENSIONS_DIR}:/extensions:delegated'
      - './${SHARED_DIR}:/mnt:rw,delegated'
    environment:
      - 'PHP_EXTENSIONS=${PHP_EXTENSIONS} xdebug'
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_FPM_XDEBUG}
    depends_on:
      db:
        condition: service_started
  web:
    hostname: ${DC_HOSTNAME_WEB}
    image: magento/magento-cloud-docker-nginx:${DC_IMAGE_NGINX_VERSION}
    extends: generic
    volumes:
      - './${MAGENTO_DIR}:${MAGENTO_ROOT}:delegated'
      - './${EXTENSIONS_DIR}:/extensions:delegated'
      - './${SHARED_DIR}:/mnt:rw,delegated'
    environment:
      - WITH_XDEBUG=1
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_WEB}
    depends_on:
      fpm:
        condition: service_started
  tls:
    hostname: ${DC_HOSTNAME_TLS}
    image: magento/magento-cloud-docker-nginx:${DC_IMAGE_NGINX_VERSION}
    extends: generic
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_TLS}
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - UPSTREAM_HOST=web
      - UPSTREAM_PORT=8080
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      web:
        condition: service_started
  db:
    hostname: ${DC_HOSTNAME_DB}
    image: mariadb:${DC_IMAGE_MYSQL_VERSION}
    shm_size: 2gb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_EXPOSED_PORT}:3306'
    volumes:
      - './mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './mysql/mariadb.conf.d:/etc/mysql/mariadb.conf.d'
      - './${SHARED_DIR}:/mnt:rw,delegated'
      - 'db-data:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -p${MYSQL_PASSWORD}'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_DB}
  rabbitmq:
    hostname: ${DC_HOSTNAME_RABBITMQ}
    image: rabbitmq:${DC_IMAGE_RABBITMQ_VERSION}
    ports:
      - ${EXPOSE_RABBITMQ_PORT}:15672
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_RABBITMQ}
  mailhog:
    hostname: ${DC_HOSTNAME_MAILHOG}
    image: magento/magento-cloud-docker-mailhog:${DC_IMAGE_MAILHOG_VERSION}
    ports:
      - '${EXPOSE_MAILHOG_SMTP_PORT}:1025'
      - '${EXPOSE_MAILHOG_WEB_PORT}:8025'
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_MAILHOG}
  opensearch:
    hostname: ${DC_HOSTNAME_OPENSEARCH}
    image: magento/magento-cloud-docker-opensearch:${DC_IMAGE_OPENSEARCH_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - discovery.seed_hosts=opensearch
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_OPENSEARCH}
  redis:
    hostname: ${DC_HOSTNAME_REDIS}
    image: redis:${DC_IMAGE_REDIS_VERSION}
    ports:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_REDIS}
  redis-commander:
    hostname: ${DC_HOSTNAME_REDIS_COMMANDER}
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=${DC_HOSTNAME_REDIS}
    ports:
      - '${EXPOSE_REDIS_COMMANDER_PORT}:8081'
    networks:
      magento:
        aliases:
          - ${DC_HOSTNAME_REDIS_COMMANDER}
    depends_on:
      redis:
        condition: service_started
volumes:
  db-data: {  }
networks:
  magento:
    driver: bridge
